[package]
name = "compiler"
version = "0.1.1"
edition = "2024"
rust-version = "1.86"

[dependencies]
parser = { path = "../parser" }
serde = { version = "1.0.217", features = ["derive"] }

[lib]
doctest = false
