[package]
name = "faradayc"
version = "0.1.1"
edition = "2024"

[dependencies]
compiler = { path = "../compiler" }
parser = { path = "../parser" }
pathbufd = "0.1.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
