[package]
name = "faradayc"
version = "0.1.0"
edition = "2024"

[dependencies]
compiler = { path = "../compiler" }
parser = { path = "../parser" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
